const TASK_WAITING_STATUS = 0;
const TASK_RUNNING_STATUS = 1;
const TASK_COMPLETE_STATUS = 2;


const HEADER_GETWAY_REQUEST_TASK = 0;
const HEADER_SERVER_SEND_TASK = 1;
const HEADER_GATEWAY_SEND_SENSOR_VALUE = 2;
const HEADER_GATEWAY_SEND_TASK_STATUS = 3;
const HEADER_GATEWAY_SEND_ACK = 4;
const HEADER_SERVER_DELETE_TASK = 5;

export default {
  TASK_WAITING_STATUS,
  TASK_RUNNING_STATUS,
  TASK_COMPLETE_STATUS,
  
  HEADER_GETWAY_REQUEST_TASK,
  HEADER_SERVER_SEND_TASK,
  HEADER_GATEWAY_SEND_SENSOR_VALUE,
  HEADER_GATEWAY_SEND_TASK_STATUS,
  HEADER_GATEWAY_SEND_ACK,
  HEADER_SERVER_DELETE_TASK
  
}